version: "3.3"
services:
  # swagger.yml作成
  swagger-merger:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./models:/models
      - ./open_api.yml:/open_api.yml
      - './swagger.yml:/swagger.yml'
    command:
      swagger-merger -i open_api.yml

  # swagger表示
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - './swagger.yml:/usr/share/nginx/html/swagger.yml'
    environment:
      API_URL: swagger.yml
    ports:
      - '8080:8080'
    # swagger-mergerでswagger.ymlを更新してから立ち上げる
    depends_on:
      - "swagger-merger"
    
  # モックサーバーを構築
  prism:
    image: stoplight/prism:3
    volumes:
      - ./swagger.yml:/swagger.yml
    ports:
      - "3000:4010"
    command: mock -h 0.0.0.0 /swagger.yml
    depends_on:
      - "swagger-merger"

# コンテナ間でswagger.ymlを共有
volumes:
  swagger.yml:
    driver: local